site_name: enkeksi's documentation

theme:
    name: readthedocs
    navigation_depth: 1
    prev_next_buttons_location: top

nav:
  - Home: index.md
  - Demo (template): demo_tmpl.md
  - Demo: demo.md
