"""Markdown parsing and SQL execution for enkeksi."""

from __future__ import annotations

import re
import shlex
import sqlite3
from collections.abc import Sequence
from dataclasses import dataclass, replace
from pathlib import Path
from typing import Any, Protocol, cast

from markdown_it import MarkdownIt
from tabulate import tabulate

_GENERATED_RE = re.compile(
    r"\n*<!-- enkeksi:begin -->.*?<!-- enkeksi:end -->\n*", re.DOTALL
)


class EnkeksiError(RuntimeError):
    """Raised when a Markdown SQL block cannot be executed."""


class Cursor(Protocol):
    description: Sequence[Sequence[Any]] | None

    def execute(self, sql: str) -> Any: ...

    def fetchall(self) -> Sequence[Sequence[Any]]: ...


class Connection(Protocol):
    def cursor(self) -> Cursor: ...

    def commit(self) -> None: ...

    def rollback(self) -> None: ...

    def close(self) -> None: ...


@dataclass(frozen=True, slots=True)
class RenderOptions:
    """Options controlling SQL execution and rendered Markdown."""

    engine: str = "sqlite"
    database: str = ":memory:"
    read_only: bool | None = None
    keep_going: bool = False
    check: bool = False
    default_table_format: str = "github"


@dataclass(frozen=True, slots=True)
class BlockOptions:
    show_input: bool = True
    show_output: bool = True
    show_headers: bool = True
    caption: str | None = None
    table_format: str = "github"


@dataclass(frozen=True, slots=True)
class QueryResult:
    headers: tuple[str, ...]
    rows: tuple[tuple[Any, ...], ...]


def strip_generated_output(markdown: str) -> str:
    """Remove output regions generated by an earlier enkeksi run."""

    return _GENERATED_RE.sub("\n", markdown)


def split_sql_statements(sql: str) -> list[str]:
    """Split SQL at semicolons outside strings and comments."""

    statements: list[str] = []
    buffer: list[str] = []
    quote: str | None = None
    line_comment = False
    block_comment = False
    index = 0

    while index < len(sql):
        char = sql[index]
        next_char = sql[index + 1] if index + 1 < len(sql) else ""
        buffer.append(char)

        if line_comment:
            if char == "\n":
                line_comment = False
        elif block_comment:
            if char == "*" and next_char == "/":
                buffer.append(next_char)
                index += 1
                block_comment = False
        elif quote is not None:
            if char == quote:
                if next_char == quote:
                    buffer.append(next_char)
                    index += 1
                else:
                    quote = None
        elif char in {"'", '"', "`"}:
            quote = char
        elif char == "-" and next_char == "-":
            buffer.append(next_char)
            index += 1
            line_comment = True
        elif char == "/" and next_char == "*":
            buffer.append(next_char)
            index += 1
            block_comment = True
        elif char == ";":
            statement = "".join(buffer).strip()
            if statement:
                statements.append(statement)
            buffer.clear()
        index += 1

    remainder = "".join(buffer).strip()
    if remainder:
        statements.append(remainder)
    return statements


def _parse_directives(value: str, defaults: BlockOptions) -> BlockOptions:
    options = defaults
    try:
        tokens = shlex.split(value)
    except ValueError as error:
        raise EnkeksiError(f"Invalid enkeksi directives: {error}") from error

    index = 0
    while index < len(tokens):
        token = tokens[index].lstrip("-")
        key, separator, raw_value = token.partition("=")
        key = key.replace("_", "-")

        if key in {"caption", "table-format"} and not separator:
            index += 1
            if index >= len(tokens):
                raise EnkeksiError(f"Directive {key!r} requires a value")
            raw_value = tokens[index]

        if key == "hide-input":
            options = replace(options, show_input=False)
        elif key == "hide-output":
            options = replace(options, show_output=False)
        elif key == "hide-headers":
            options = replace(options, show_headers=False)
        elif key == "caption":
            options = replace(options, caption=raw_value)
        elif key == "table-format":
            options = replace(options, table_format=raw_value)
        elif key:
            raise EnkeksiError(f"Unknown enkeksi directive: {key}")
        index += 1
    return options


def _block_options(
    info: str, code: str, default_format: str
) -> tuple[BlockOptions, str]:
    options = BlockOptions(table_format=default_format)
    info_parts = info.strip().split(maxsplit=1)
    if len(info_parts) == 2:
        options = _parse_directives(info_parts[1], options)

    lines = code.splitlines()
    if lines:
        first = lines[0].strip()
        directive_text: str | None = None
        if first.lower().startswith("-- enkeksi:"):
            directive_text = first.split(":", 1)[1].strip()
        elif first.startswith("--") and any(
            marker in first
            for marker in (
                "--hide-input",
                "--hide-output",
                "--hide-headers",
                "--caption",
                "--table-format",
            )
        ):
            directive_text = first[2:].strip()
        if directive_text is not None:
            options = _parse_directives(directive_text, options)
            code = "\n".join(lines[1:])
    return options, code.strip()


def _connect(options: RenderOptions) -> Connection:
    read_only = options.read_only
    if read_only is None:
        read_only = options.database != ":memory:"

    if options.engine == "sqlite":
        if read_only and options.database != ":memory:":
            database = Path(options.database).resolve().as_uri() + "?mode=ro"
            return sqlite3.connect(database, uri=True)
        return sqlite3.connect(options.database)

    if options.engine == "duckdb":
        try:
            import duckdb
        except ImportError as error:
            raise EnkeksiError(
                "DuckDB support is optional; install it with `uv add enkeksi[duckdb]`."
            ) from error
        return cast(Connection, duckdb.connect(options.database, read_only=read_only))

    raise EnkeksiError(f"Unsupported database engine: {options.engine}")


def _execute(connection: Connection, sql: str) -> QueryResult | None:
    statements = split_sql_statements(sql)
    if not statements:
        return None

    cursor = connection.cursor()
    result: QueryResult | None = None
    try:
        for statement in statements:
            cursor.execute(statement)
            if cursor.description is not None:
                headers = tuple(str(column[0]) for column in cursor.description)
                rows = tuple(tuple(row) for row in cursor.fetchall())
                result = QueryResult(headers, rows)
        connection.commit()
    except Exception as error:
        connection.rollback()
        raise EnkeksiError(str(error)) from error
    return result


def _render_result(result: QueryResult, options: BlockOptions) -> str:
    headers: Sequence[str] = result.headers if options.show_headers else ()
    table = tabulate(result.rows, headers=headers, tablefmt=options.table_format)
    parts = ["<!-- enkeksi:begin -->"]
    if options.caption:
        parts.extend((f"**{options.caption}**", ""))
    parts.append(table)
    parts.append("<!-- enkeksi:end -->")
    return "\n".join(parts)


def _render_error(error: EnkeksiError) -> str:
    return "\n".join(
        (
            "<!-- enkeksi:begin -->",
            "```text",
            f"enkeksi error: {error}",
            "```",
            "<!-- enkeksi:end -->",
        )
    )


def render_markdown(markdown: str, options: RenderOptions | None = None) -> str:
    """Execute SQL fences and return Markdown containing their results.

    Generated regions are replaced on every run, making in-place rendering
    idempotent. SQL errors raise :class:`EnkeksiError` unless ``keep_going`` is
    enabled.
    """

    options = options or RenderOptions()
    source = strip_generated_output(markdown)
    lines = source.splitlines()
    trailing_newline = source.endswith("\n")
    tokens = MarkdownIt("commonmark").parse(source)
    fences = []
    for token in tokens:
        info_parts = token.info.strip().split(maxsplit=1)
        if (
            token.type == "fence"
            and token.map is not None
            and info_parts
            and info_parts[0].lower() == "sql"
        ):
            fences.append(token)

    replacements: list[tuple[int, int, list[str]]] = []
    connection = _connect(options)
    try:
        for token in fences:
            assert token.map is not None
            start, end = token.map
            block_options, sql = _block_options(
                token.info, token.content, options.default_table_format
            )
            replacement: list[str] = []
            if block_options.show_input:
                replacement.extend(("```sql", *sql.splitlines(), "```"))

            try:
                result = _execute(connection, sql)
            except EnkeksiError as error:
                if not options.keep_going:
                    raise EnkeksiError(
                        f"SQL block starting on line {start + 1}: {error}"
                    ) from error
                if block_options.show_output and not options.check:
                    if replacement:
                        replacement.append("")
                    replacement.extend(_render_error(error).splitlines())
            else:
                if (
                    result is not None
                    and block_options.show_output
                    and not options.check
                ):
                    if replacement:
                        replacement.append("")
                    rendered_result = _render_result(result, block_options)
                    replacement.extend(rendered_result.splitlines())
            replacements.append((start, end, [] if options.check else replacement))
    finally:
        connection.close()

    for start, end, replacement in reversed(replacements):
        lines[start:end] = replacement

    if options.check:
        return ""
    rendered = "\n".join(lines)
    if trailing_newline:
        rendered += "\n"
    return rendered
